import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
const inter = Inter({ subsets: ["latin"] });
import { Button } from "@/components/ui/button";
import { Folders, Heart, Image } from "lucide-react";
import Link from "next/link";
function SideMenu() {
  return (
    <>
      <div className="pb-12 w-1/5">
        <div className="space-y-4 py-4">
          <div className="px-3 py-2">
            <h2 className="mb-2 px-4 text-lg font-semibold tracking-tight">
              Manage
            </h2>
            <div className="space-y-1">
              <Button
                variant="secondary"
                className="w-full justify-start gap-2"
              >
                <Image />
                <Link href="/gallary">Gallary</Link>
              </Button>
              <Button variant="ghost" className="w-full justify-start gap-2">
                <Folders />
                <Link href="/albums">Albums</Link>
              </Button>
              <Button variant="ghost" className="w-full justify-start gap-2">
                <Heart />
                <Link href="/favorite">Favorites</Link>
              </Button>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body suppressHydrationWarning className={inter.className}>
        <div className="border-b">
          <div className="flex h-16 items-center px-4 container mx-auto">
            Hello
            <div className="ml-auto flex items-center space-x-4">
              <Avatar>
                <AvatarImage
                  src="https://github.com/shadcn.png"
                  alt="@shadcn"
                />
                <AvatarFallback>CN</AvatarFallback>
              </Avatar>
            </div>
          </div>
        </div>
        <div className="flex">
          <SideMenu />
          <div className="w-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
